# Generated by Django 5.0.2 on 2024-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('paciente_familiar', models.IntegerField()),
                ('presentacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('relacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('internacion', models.DateField(max_length=30)),
                ('externacion', models.DateField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionPacienteFamiliar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('paciente', models.IntegerField()),
                ('familiar', models.IntegerField()),
            ],
        ),
    ]
