# Generated by Django 5.0.2 on 2024-03-01 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], max_length=10)),
                ('tipo_edad', models.CharField(choices=[('menor', 'Menor'), ('adulto', 'Adulto')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('internacion', models.DateField()),
                ('externacion', models.DateField(blank=True, null=True)),
                ('persona_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConstancias.persona')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionPacienteFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(max_length=100)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConstancias.paciente')),
                ('persona_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConstancias.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presentacion', models.DateField()),
                ('relacion_paciente_familiar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConstancias.relacionpacientefamiliar')),
            ],
        ),
        migrations.AddConstraint(
            model_name='relacionpacientefamiliar',
            constraint=models.UniqueConstraint(fields=('paciente_id', 'persona_dni'), name='pk_relacion_compuesta'),
        ),
    ]
