# Generated by Django 5.0.2 on 2024-03-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConstancias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='articulo',
            field=models.CharField(default='', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='persona',
            name='constancia_a_solicitud',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='terminacion',
            field=models.CharField(default='', editable=False, max_length=5),
        ),
    ]
