# Generated by Django 5.0.2 on 2024-02-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConstancias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constancia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='constancia',
            name='paciente_familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConstancias.relacionpacientefamiliar'),
        ),
        migrations.AlterField(
            model_name='relacionpacientefamiliar',
            name='familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConstancias.familiar'),
        ),
        migrations.AlterField(
            model_name='relacionpacientefamiliar',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConstancias.paciente'),
        ),
    ]
