# Generated by Django 5.0.2 on 2024-03-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConstancias', '0002_persona_articulo_persona_constancia_a_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='articulo',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='persona',
            name='constancia_a_solicitud',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='terminacion',
            field=models.CharField(default='', max_length=5),
        ),
    ]
