# Generated by Django 5.0.2 on 2024-02-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConstancias', '0002_alter_constancia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='relacion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='externacion',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
