# Generated by Django 5.0.2 on 2024-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConstancias', '0003_alter_familiar_relacion_alter_paciente_externacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='relacion',
        ),
        migrations.AddField(
            model_name='relacionpacientefamiliar',
            name='relacion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
