# Generated by Django 5.0.2 on 2024-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConstancias', '0004_remove_familiar_relacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionpacientefamiliar',
            name='relacion',
            field=models.CharField(max_length=30),
        ),
    ]
