# Generated by Django 5.0.2 on 2024-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConstancias', '0005_alter_relacionpacientefamiliar_relacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='externacion',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
