# Generated by Django 5.0.2 on 2024-02-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConstancias', '0006_alter_paciente_externacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.CharField(max_length=30, verbose_name='Adulto/Menor'),
        ),
    ]
