# Generated by Django 5.0.2 on 2024-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConstancias', '0007_alter_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionpacientefamiliar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
