"""Agregar tabla plans

Revision ID: 11177f7c157d
Revises: 5e6d5503cf5d
Create Date: 2025-05-11 14:11:36.296358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11177f7c157d'
down_revision: Union[str, None] = '5e6d5503cf5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name='plan_entity_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'entity_id', name='uq_plan_name_entity_id')
    )
    op.create_index(op.f('ix_plans_entity_id'), 'plans', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_entity_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
