"""Agregar número HC paciente, agregar is_patient a persona

Revision ID: 3acde6afbb27
Revises: 743067dae559
Create Date: 2025-05-19 08:44:49.862921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acde6afbb27'
down_revision: Union[str, None] = '743067dae559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('clinical_history_number', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_patients_clinical_history_number'), 'patients', ['clinical_history_number'], unique=True)
    op.add_column('persons', sa.Column('is_patient', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'is_patient')
    op.drop_index(op.f('ix_patients_clinical_history_number'), table_name='patients')
    op.drop_column('patients', 'clinical_history_number')
    # ### end Alembic commands ###
