"""Agregar a columna registration unique=True

Revision ID: 5e6d5503cf5d
Revises: 80e947706f08
Create Date: 2025-05-10 20:30:10.658422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6d5503cf5d'
down_revision: Union[str, None] = '80e947706f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'professionals', ['national_registration'])
    op.create_unique_constraint(None, 'professionals', ['provincial_registration'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professionals', type_='unique')
    op.drop_constraint(None, 'professionals', type_='unique')
    # ### end Alembic commands ###
