"""Agregar tabla professionals

Revision ID: 72139173c9cf
Revises: 845e031b0972
Create Date: 2025-05-10 02:55:05.526318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72139173c9cf'
down_revision: Union[str, None] = '845e031b0972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('national_registration', sa.Integer(), nullable=False),
    sa.Column('provincial_registration', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='professional_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature')
    )
    op.create_index(op.f('ix_professionals_user_id'), 'professionals', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professionals_user_id'), table_name='professionals')
    op.drop_table('professionals')
    # ### end Alembic commands ###
