"""Agregar tabla evaluaciones

Revision ID: 7be139270a0b
Revises: 909d5ac3c29a
Create Date: 2025-06-02 11:34:44.057875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be139270a0b'
down_revision: Union[str, None] = '909d5ac3c29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report', sa.Text(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.Enum('EXTERNAL', 'DAY_HOSPITAL', 'INTERNMENT', name='mode_enum'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='evaluation_patient_id'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name='evaluation_professional_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_closed_at'), 'evaluations', ['closed_at'], unique=False)
    op.create_index(op.f('ix_evaluations_patient_id'), 'evaluations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_evaluations_professional_id'), 'evaluations', ['professional_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_professional_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_patient_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_closed_at'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
