"""Corregir registratinos como opcionales en modelo Professional

Revision ID: 80e947706f08
Revises: 407e21b4ec63
Create Date: 2025-05-10 03:06:07.977534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e947706f08'
down_revision: Union[str, None] = '407e21b4ec63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('professionals', 'national_registration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('professionals', 'provincial_registration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('professionals', 'provincial_registration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('professionals', 'national_registration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
