"""Agregar columna file para el legajo del user

Revision ID: 909d5ac3c29a
Revises: e3bac4cbc3dd
Create Date: 2025-05-30 13:08:49.482956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909d5ac3c29a'
down_revision: Union[str, None] = 'e3bac4cbc3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('file', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_file'), 'users', ['file'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_file'), table_name='users')
    op.drop_column('users', 'file')
    # ### end Alembic commands ###
