"""Agregar columna is_professional

Revision ID: e3bac4cbc3dd
Revises: e5ec7bf6b1d7
Create Date: 2025-05-27 14:00:01.485904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bac4cbc3dd'
down_revision: Union[str, None] = 'e5ec7bf6b1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Primero la columna se agrega como nullable con un default temporal
    op.add_column('users', sa.Column('is_professional', sa.Boolean(), nullable=True))

    # 2. Luego se asigna el valor default a las filas existentes
    op.execute("UPDATE users SET is_professional = false")

    # 3. Después se cambia a NOT NULL
    op.alter_column('users', 'is_professional', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_professional')
    # ### end Alembic commands ###
