"""Agregar tabla patients

Revision ID: e9e2d294a793
Revises: 11177f7c157d
Create Date: 2025-05-12 10:15:14.593261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e2d294a793'
down_revision: Union[str, None] = '11177f7c157d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_1', sa.String(), nullable=False),
    sa.Column('phone_2', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_last_name'), 'persons', ['last_name'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_code', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name='patient_person_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='plan_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_index(op.f('ix_patients_plan_id'), 'patients', ['plan_id'], unique=False)
    op.drop_constraint('plan_entity_id', 'plans', type_='foreignkey')
    op.create_foreign_key('plan_entity_id', 'plans', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('professional_user_id', 'professionals', type_='foreignkey')
    op.create_foreign_key('professional_user_id', 'professionals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('professional_user_id', 'professionals', type_='foreignkey')
    op.create_foreign_key('professional_user_id', 'professionals', 'users', ['user_id'], ['id'])
    op.drop_constraint('plan_entity_id', 'plans', type_='foreignkey')
    op.create_foreign_key('plan_entity_id', 'plans', 'entities', ['entity_id'], ['id'])
    op.drop_index(op.f('ix_patients_plan_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_persons_last_name'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
