"""Agregar nullable=True a phone_2 y email

Revision ID: ee2491442813
Revises: e9e2d294a793
Create Date: 2025-05-12 10:21:50.001757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2491442813'
down_revision: Union[str, None] = 'e9e2d294a793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'phone_2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('persons', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('persons', 'phone_2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
