"""Agregar columna DNI a persona

Revision ID: fb41c939cbb8
Revises: 3acde6afbb27
Create Date: 2025-05-20 13:29:17.168381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb41c939cbb8'
down_revision: Union[str, None] = '3acde6afbb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('dni', sa.String(), nullable=False))
    op.create_index(op.f('ix_persons_dni'), 'persons', ['dni'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_dni'), table_name='persons')
    op.drop_column('persons', 'dni')
    # ### end Alembic commands ###
